kind: pipeline
name: default

steps:
- name: docker-php-fpm
  image: plugins/docker
  settings:
    dockerfile: php-fpm/Dockerfile
    repo: tlemarchand/nextcloud-php-fpm
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    build_args:
      - NEXTCLOUD_VERSION=16.0.4

- name: docker-nginx
  image: plugins/docker
  settings:
    dockerfile: nginx/Dockerfile
    repo: tlemarchand/nextcloud-nginx
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    build_args:
      - NEXTCLOUD_VERSION=16.0.4
