global_variables:
  nextcloud_tag: &nextcloud_tag 19.0.0
  nextcloud_version: &nextcloud_version NEXTCLOUD_VERSION=19.0.0

kind: pipeline
name: default

steps:
- name: tag
  image: debian:10
  environment:
    NEXTCLOUD_TAG: *nextcloud_tag
  commands:
  - echo -n latest,$${NEXTCLOUD_TAG},$${NEXTCLOUD_TAG}-$DRONE_BUILD_NUMBER > .tags

- name: docker-php-fpm
  image: plugins/docker
  settings:
    dockerfile: php-fpm/Dockerfile
    repo: tlemarchand/nextcloud-php-fpm
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    build_args:
      - *nextcloud_version

- name: docker-nginx
  image: plugins/docker
  settings:
    dockerfile: nginx/Dockerfile
    repo: tlemarchand/nextcloud-nginx
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    build_args:
      - *nextcloud_version

- name: quay-php-fpm
  image: plugins/docker
  settings:
    dockerfile: php-fpm/Dockerfile
    repo: quay.io/tlemarchand/nextcloud-php-fpm
    username:
      from_secret: quay_username
    password:
      from_secret: quay_password
    build_args:
      - *nextcloud_version
    registry: quay.io

- name: quay-nginx
  image: plugins/docker
  settings:
    dockerfile: nginx/Dockerfile
    repo: quay.io/tlemarchand/nextcloud-nginx
    username:
      from_secret: quay_username
    password:
      from_secret: quay_password
    build_args:
      - *nextcloud_version
    registry: quay.io